#!/bin/bash

if [ ! -z $TABLES_DIR ]; then
	cp -r $TABLES_DIR/syscall-names.text $TABLES_DIR/tables data/
fi

for table in data/tables/syscalls-*
do
	tmp=${table#data/tables/}
	arch=${tmp#syscalls-}
	
	echo "# Content autogenerated. Do not edit." > system_calls/tables/${arch}.py
	echo "" >> system_calls/tables/${arch}.py
	echo "syscalls_${arch} = {" >> system_calls/tables/${arch}.py
	grep -P '\t' $table | sed -e 's/^\(.*\)\t\(.*\)$/    "\1": \2,/g' >> system_calls/tables/${arch}.py
	echo "}" >> system_calls/tables/${arch}.py
done

echo "# Content autogenerated. Do not edit." > system_calls/tables/names.py
echo "syscalls_names = [" >>system_calls/tables/names.py
sed -e 's/^\(.*\)/    "\1",/g' data/syscall-names.text >>system_calls/tables/names.py
echo "]" >>system_calls/tables/names.py

