#!/bin/bash

for table in tables/syscalls-*
do
	tmp=${table#tables/}
	arch=${tmp#syscalls-}
	
	echo "#!/usr/bin/python3" > syscalls/tables/${arch}.py
	echo "" >> syscalls/tables/${arch}.py
	echo "# Content autogenerated. Do not edit." >> syscalls/tables/${arch}.py
	echo "" >> syscalls/tables/${arch}.py
	echo "syscalls_${arch} = {" >> syscalls/tables/${arch}.py
	grep -P '\t' $table | sed -e 's/^\(.*\)\t\(.*\)$/    "\1": \2,/g' >> syscalls/tables/${arch}.py
	echo "}" >> syscalls/tables/${arch}.py
done

echo "#!/usr/bin/python3" >syscalls/tables/names.py
echo "" >>syscalls/tables/names.py
echo "syscalls_names = [" >>syscalls/tables/names.py
sed -e 's/^\(.*\)/    "\1",/g' syscall-names.text >>syscalls/tables/names.py
echo "]" >>syscalls/tables/names.py

